/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import database.IBilgicontroller;
import database.transactions.HesapBilgileri;
import database.transactions.TelNoYenileme;
import gui.ayarlar.Actionayarlari;
import gui.ayarlar.Dialog;
import gui.ayarlar.IDuzenleyici;
import gui.ayarlar.Iconayarlari;
import gui.ayarlar.Textayarlari;
import javax.swing.JOptionPane;



/**
 *
 * @author EYMEN SEZEN
 */
public final class ayarlarekrani extends javax.swing.JFrame implements IDuzenleyici,IBilgicontroller {

    /**
     * Creates new form ayarlarekrani
     */
    private TelNoYenileme telNoyenilemeobject=null;
    private String eskiTelNo=null;
    private final String SIFRE_TEXT_ORIGINAL ="**********";//sifre kısmı icin bg
    public ayarlarekrani() {
        initComponents();
        getedits();}

    @Override
    public void getedits() {
      this.setVisible(true);
      this.setLocationRelativeTo(null);
      /**/
        this.setResizable(false);
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
//OPSİYONELLER
      Textayarlari.setonlynumber(telnotext);
      Textayarlari.setlimitayarla(telnotext, 11);
        this.telnotext.setText(gethesapbilgileri().getTelno()); 
        this.eskiTelNo=telnotext.getText();
        this.kullanicilabel.setText("Sayın "+gethesapbilgileri().getAdsoyad());
    }

    @Override
    public boolean bilgilergecerlimi() {
return !(this.telnotext.getText().equals(""));
        }

    @Override
    public HesapBilgileri gethesapbilgileri() {
     return HesapBilgileri.getInstance();
    }

    public TelNoYenileme getTelNoyenilemeobject() {
          if (this.telNoyenilemeobject == null) {
            telNoyenilemeobject = new TelNoYenileme();
        }
        return telNoyenilemeobject;

            
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ayarlarekranıpanel = new javax.swing.JPanel();
        cıkıslabel = new javax.swing.JLabel();
        kullanicilabel = new javax.swing.JLabel();
        telnolabel = new javax.swing.JLabel();
        telnotext = new javax.swing.JTextField();
        yenilemeiconlabel = new javax.swing.JLabel();
        şifrelabel = new javax.swing.JLabel();
        şifretext = new javax.swing.JTextField();
        şifreiconlabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ayarlarekranıpanel.setBackground(new java.awt.Color(204, 204, 255));

        cıkıslabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/iconlar/cıkısicon.png"))); // NOI18N
        cıkıslabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cıkıslabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cıkıslabelMouseClicked(evt);
            }
        });

        kullanicilabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        kullanicilabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        kullanicilabel.setText("Sayın [KULLANICI ADI SOYADI]");

        telnolabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        telnolabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        telnolabel.setText("Telefon numaranız:");

        telnotext.setEnabled(false);

        yenilemeiconlabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\EYMEN SEZEN\\OneDrive\\Belgeler\\NetBeansProjects\\Eymenbank\\src\\gui\\iconlar\\yenilemeicon.png")); // NOI18N
        yenilemeiconlabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        yenilemeiconlabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                yenilemeiconlabelMouseClicked(evt);
            }
        });

        şifrelabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        şifrelabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        şifrelabel.setText("Şifreniz:");

        şifretext.setText("************");
        şifretext.setEnabled(false);
        şifretext.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                şifretextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                şifretextFocusLost(evt);
            }
        });

        şifreiconlabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\EYMEN SEZEN\\OneDrive\\Belgeler\\NetBeansProjects\\Eymenbank\\src\\gui\\iconlar\\yenilemeicon.png")); // NOI18N
        şifreiconlabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        şifreiconlabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                şifreiconlabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ayarlarekranıpanelLayout = new javax.swing.GroupLayout(ayarlarekranıpanel);
        ayarlarekranıpanel.setLayout(ayarlarekranıpanelLayout);
        ayarlarekranıpanelLayout.setHorizontalGroup(
            ayarlarekranıpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ayarlarekranıpanelLayout.createSequentialGroup()
                .addGroup(ayarlarekranıpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ayarlarekranıpanelLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(ayarlarekranıpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(şifrelabel)
                            .addComponent(telnolabel))
                        .addGap(36, 36, 36)
                        .addGroup(ayarlarekranıpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(şifretext, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                            .addComponent(telnotext))
                        .addGap(18, 18, 18)
                        .addGroup(ayarlarekranıpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(yenilemeiconlabel)
                            .addComponent(şifreiconlabel)))
                    .addGroup(ayarlarekranıpanelLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(cıkıslabel)
                        .addGap(18, 18, 18)
                        .addComponent(kullanicilabel, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        ayarlarekranıpanelLayout.setVerticalGroup(
            ayarlarekranıpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ayarlarekranıpanelLayout.createSequentialGroup()
                .addGroup(ayarlarekranıpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kullanicilabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cıkıslabel))
                .addGap(158, 158, 158)
                .addGroup(ayarlarekranıpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ayarlarekranıpanelLayout.createSequentialGroup()
                        .addGroup(ayarlarekranıpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(yenilemeiconlabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ayarlarekranıpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(telnolabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(telnotext, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(37, 37, 37)
                        .addGroup(ayarlarekranıpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(şifrelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(şifretext, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(şifreiconlabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 125, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ayarlarekranıpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ayarlarekranıpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cıkıslabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cıkıslabelMouseClicked
        Actionayarlari.setVisible(this, new hesapekrani());
    }//GEN-LAST:event_cıkıslabelMouseClicked
    private int clickCounter=0;
    private void yenilemeiconlabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yenilemeiconlabelMouseClicked
        if(clickCounter==0){
        telnotext.setEnabled(true);//aktiflikkkkkkkk
       // Iconayarlari.changeIcon(yenilemeiconlabel, "yenileme2");
        //ARKADAŞ İKON DEĞİŞTİRDİ AMA BEN HATA ALDIĞIM İÇİN DEĞİŞTİRMEDİM.....
        clickCounter++;
        }
        else{
        telnotext.setEnabled(false);
        this.telNoYenile();
         
     //    Iconayarlari.setOriginalIcon(yenilemeiconlabel);
        clickCounter=0;
        }
    }//GEN-LAST:event_yenilemeiconlabelMouseClicked
    private void telNoYenile()
    {
        if(this.bilgilergecerlimi())
        {
            String yeniTelNo=this.telnotext.getText().trim();   
            getTelNoyenilemeobject().setTelNo(yeniTelNo);
            if(getTelNoyenilemeobject().telNoYenilendiMi())
            {
            Dialog.ozelMesajGoster(this, "Telefon numarası: "+yeniTelNo+" olarak güncellenmiştir");
            }
            else
            {
            Dialog.ozelMesajGoster(this, "Yenileme başarısız oldu.");
            this.telnotext.setText(eskiTelNo);//eski numarayı tekrar set et
            }
        }
        else
        {
        Dialog.bosOlamazMesajiGoster(this);
        this.telnotext.setText(eskiTelNo);//eski numarayı tekrar set et

        }
    
    }
    private void şifreiconlabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_şifreiconlabelMouseClicked
        Actionayarlari.setVisible(this, new şifreyenilemeekrani());
    }//GEN-LAST:event_şifreiconlabelMouseClicked

    private void şifretextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_şifretextFocusGained
       Textayarlari.checkthefocusgained(şifretext, SIFRE_TEXT_ORIGINAL);
    }//GEN-LAST:event_şifretextFocusGained

    private void şifretextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_şifretextFocusLost
        Textayarlari.checkthefocuslost(şifretext);
    }//GEN-LAST:event_şifretextFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ayarlarekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ayarlarekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ayarlarekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ayarlarekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ayarlarekrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ayarlarekranıpanel;
    private javax.swing.JLabel cıkıslabel;
    private javax.swing.JLabel kullanicilabel;
    private javax.swing.JLabel telnolabel;
    private javax.swing.JTextField telnotext;
    private javax.swing.JLabel yenilemeiconlabel;
    private javax.swing.JLabel şifreiconlabel;
    private javax.swing.JLabel şifrelabel;
    private javax.swing.JTextField şifretext;
    // End of variables declaration//GEN-END:variables
}
