/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import database.IBilgicontroller;
import database.transactions.HesapBilgileri;
import database.transactions.Kullanıcıbasvuru;
import gui.ayarlar.Actionayarlari;
import gui.ayarlar.Butonayarlari;
import gui.ayarlar.Dialog;
import gui.ayarlar.IDuzenleyici;
import gui.ayarlar.Textayarlari;
import java.awt.Color;
import javax.swing.JOptionPane;



/**
 *
 * @author EYMEN SEZEN
 */
public final class basvuruekrani extends javax.swing.JFrame implements IDuzenleyici,IBilgicontroller {

    private Kullanıcıbasvuru KullanıcıbasvuruObject=null;
    public basvuruekrani() {
        initComponents();
        getedits();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @Override
    public boolean bilgilergecerlimi() {
    return Textayarlari.textalanlarıDoluMu(basvurupaneli);
    }

    @Override
    public HesapBilgileri gethesapbilgileri() {
 return HesapBilgileri.getInstance();
    }
    
    
    @SuppressWarnings("unchecked")
    @Override
    public void getedits(){
      this.setLocationRelativeTo(null);
      basvurupaneli.setFocusable(true);//ekrana focuslandı
       /**/
        this.setResizable(false);
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
//OPSİYONELLER
      Textayarlari.setonlyAlphabetic(adsoyadtexti);
      Textayarlari.setonlynumber(telnotext);//sadece rakam
      Textayarlari.setonlynumber(tcnotext);
      Textayarlari.setonlyAlphabetic(güvenlikcevaptext);//sadece harf
      Textayarlari.setlimitayarla(tcnotext, 11);
      Textayarlari.setlimitayarla(telnotext, 11);
    }

    public Kullanıcıbasvuru getKullanıcıbasvuruObject() {//getterı
        
        if(this.KullanıcıbasvuruObject==null)
        {
        KullanıcıbasvuruObject=new Kullanıcıbasvuru();//yeni bir obje oluşturmak için
        }
        return KullanıcıbasvuruObject;
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        basvurupaneli = new javax.swing.JPanel();
        güvenliksorusu = new javax.swing.JLabel();
        adsoyad = new javax.swing.JLabel();
        adsoyadtexti = new javax.swing.JTextField();
        tcno = new javax.swing.JLabel();
        tcnotext = new javax.swing.JTextField();
        tel = new javax.swing.JLabel();
        telnotext = new javax.swing.JTextField();
        kisilerbilgiler = new javax.swing.JLabel();
        güvelnliksorusu = new javax.swing.JLabel();
        güvenlikboxu = new javax.swing.JComboBox();
        güvenlikcevaptext = new javax.swing.JTextField();
        güvenlikcevaplabel = new javax.swing.JLabel();
        Basvurubutton = new javax.swing.JButton();
        Geritusu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        basvurupaneli.setBackground(new java.awt.Color(51, 153, 255));

        güvenliksorusu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        güvenliksorusu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        güvenliksorusu.setText("Güvenlik Bilgileri");

        adsoyad.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        adsoyad.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        adsoyad.setText("Ad-Soyad:");

        adsoyadtexti.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        adsoyadtexti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adsoyadtextiActionPerformed(evt);
            }
        });

        tcno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tcno.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tcno.setText("TC Kimlik No:");

        tcnotext.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tcnotext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcnotextActionPerformed(evt);
            }
        });

        tel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tel.setText("Telefon Numarası:");

        telnotext.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        telnotext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telnotextActionPerformed(evt);
            }
        });

        kisilerbilgiler.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        kisilerbilgiler.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        kisilerbilgiler.setText("Kişisel Bilgiler");

        güvelnliksorusu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        güvelnliksorusu.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        güvelnliksorusu.setText("Güvenlik Sorusu:");

        güvenlikboxu.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "evcil hayvanınızın adı?", "en sevdiğiniz nesne?", "yaşamak istediğiniz yer neresi?", "ilkokul öğretmeninizin ismi?", "ya da bir cümle girin(önerilir.)" }));

        güvenlikcevaptext.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        güvenlikcevaptext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                güvenlikcevaptextActionPerformed(evt);
            }
        });

        güvenlikcevaplabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        güvenlikcevaplabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        güvenlikcevaplabel.setText("Cevap:");

        Basvurubutton.setBackground(new java.awt.Color(255, 0, 51));
        Basvurubutton.setText("BAŞVUR");
        Basvurubutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Basvurubutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BasvurubuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BasvurubuttonMouseExited(evt);
            }
        });
        Basvurubutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BasvurubuttonActionPerformed(evt);
            }
        });

        Geritusu.setBackground(new java.awt.Color(255, 0, 51));
        Geritusu.setText("Geri");
        Geritusu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Geritusu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeritusuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout basvurupaneliLayout = new javax.swing.GroupLayout(basvurupaneli);
        basvurupaneli.setLayout(basvurupaneliLayout);
        basvurupaneliLayout.setHorizontalGroup(
            basvurupaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basvurupaneliLayout.createSequentialGroup()
                .addGroup(basvurupaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(basvurupaneliLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(basvurupaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(güvelnliksorusu, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(güvenlikcevaplabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(basvurupaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(Basvurubutton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(güvenlikcevaptext, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(basvurupaneliLayout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(güvenlikboxu, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(basvurupaneliLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(adsoyad, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(adsoyadtexti, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(basvurupaneliLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(tcno, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tcnotext, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(basvurupaneliLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(güvenliksorusu, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Geritusu, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(213, Short.MAX_VALUE))
            .addGroup(basvurupaneliLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(tel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(telnotext, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(basvurupaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(basvurupaneliLayout.createSequentialGroup()
                    .addGap(54, 54, 54)
                    .addComponent(kisilerbilgiler, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(466, Short.MAX_VALUE)))
        );

        basvurupaneliLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {güvenliksorusu, kisilerbilgiler});

        basvurupaneliLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {güvenlikboxu, telnotext});

        basvurupaneliLayout.setVerticalGroup(
            basvurupaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basvurupaneliLayout.createSequentialGroup()
                .addComponent(Geritusu)
                .addGap(43, 43, 43)
                .addGroup(basvurupaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adsoyad, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adsoyadtexti, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(basvurupaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tcno, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tcnotext, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(basvurupaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telnotext, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(güvenliksorusu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(basvurupaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(güvelnliksorusu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(güvenlikboxu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(basvurupaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(güvenlikcevaplabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(güvenlikcevaptext, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Basvurubutton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(basvurupaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(basvurupaneliLayout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addComponent(kisilerbilgiler, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(350, Short.MAX_VALUE)))
        );

        basvurupaneliLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {adsoyad, adsoyadtexti});

        basvurupaneliLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {güvenlikboxu, telnotext});

        basvurupaneliLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {güvenliksorusu, kisilerbilgiler});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(basvurupaneli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(basvurupaneli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adsoyadtextiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adsoyadtextiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adsoyadtextiActionPerformed

    private void tcnotextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcnotextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tcnotextActionPerformed

    private void telnotextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telnotextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telnotextActionPerformed

    private void güvenlikcevaptextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_güvenlikcevaptextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_güvenlikcevaptextActionPerformed

    private void GeritusuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeritusuActionPerformed
     //this.setVisible(false);
     //new girisekrani().setVisible(true);//giris ekranı true açtıkkk (yeni ekran açmadan)
    Actionayarlari.setVisible(this, new girisekrani());//bence super bir kolaylık
    }//GEN-LAST:event_GeritusuActionPerformed

    private void BasvurubuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BasvurubuttonMouseEntered
       Butonayarlari.setBgFg(Basvurubutton, Color.black, Color.yellow);
    }//GEN-LAST:event_BasvurubuttonMouseEntered

    private void BasvurubuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BasvurubuttonMouseExited
       Butonayarlari.OriginalSetBgFg(Basvurubutton);
    }//GEN-LAST:event_BasvurubuttonMouseExited

    private void BasvurubuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BasvurubuttonActionPerformed
        if(this.bilgilergecerlimi())
        {
         this.basvuruyuGerceklestir();//basvuru gerçekleşmişse
        }
        else
        {
        Dialog.bosOlamazMesajiGoster(this);
        }
            
       
    }//GEN-LAST:event_BasvurubuttonActionPerformed
     private void basvuruyuGerceklestir()
     {  /*  
         kişisel bilgiler
         */
         this.getKullanıcıbasvuruObject().setAdSoyad(this.adsoyadtexti.getText().trim());//adsoyadı alıyoruz kullanıcı objemize
         this.getKullanıcıbasvuruObject().setTcNo(this.tcnotext.getText());
         this.getKullanıcıbasvuruObject().setTelNo(this.telnotext.getText());
         //güvenlik bilgileri
         this.getKullanıcıbasvuruObject().setGuvenlikSorusu(String.valueOf( this.güvenlikboxu.getSelectedItem()));//combobox alabilmek için
         this.getKullanıcıbasvuruObject().setGuvenlikCevap(this.güvenlikcevaptext.getText().trim());
         //sistem tarafından verilecek bilgiler
         this.getKullanıcıbasvuruObject().setMusteriNo(this.randomMusteriNoAl());
         this.getKullanıcıbasvuruObject().setSifre(this.randomSifreAl());
         if(this.getKullanıcıbasvuruObject().basvuruOnaylandiMi())
         {
          Dialog.ozelMesajGoster(this, "BASVURUNUZ ONAYLANMIŞTIR.\n"
                  + "Müşteri Numaranız:"+this.getKullanıcıbasvuruObject().getMusteriNo()
                  +"\nŞifreniz:"+this.getKullanıcıbasvuruObject().getSifre());
         Actionayarlari.setVisible(this, new girisekrani());
         }
         else
         {
             Dialog.ozelMesajGoster(this, "Başvurunuz onaylanmamıştır\nLütfen bilgilerinizi kontrol ediniz.");
         
             
         }
        
       
     }
     private String randomMusteriNoAl()
     {
     String musteriNo;
     do{
     
     musteriNo=String.valueOf(1000000+(int)(Math.random()*9000000));//10milyon-1değer üretmek için
     }while(this.KullanıcıbasvuruObject.musteriNoTablodaVarMi());
     return musteriNo;
     }
     private String randomSifreAl()
     {
     String sifre;
     sifre=String.valueOf(1000+(int)(Math.random()*9000));
     return sifre;
     }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(basvuruekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(basvuruekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(basvuruekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(basvuruekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new basvuruekrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Basvurubutton;
    private javax.swing.JButton Geritusu;
    private javax.swing.JLabel adsoyad;
    private javax.swing.JTextField adsoyadtexti;
    private javax.swing.JPanel basvurupaneli;
    private javax.swing.JLabel güvelnliksorusu;
    private javax.swing.JComboBox güvenlikboxu;
    private javax.swing.JLabel güvenlikcevaplabel;
    private javax.swing.JTextField güvenlikcevaptext;
    private javax.swing.JLabel güvenliksorusu;
    private javax.swing.JLabel kisilerbilgiler;
    private javax.swing.JLabel tcno;
    private javax.swing.JTextField tcnotext;
    private javax.swing.JLabel tel;
    private javax.swing.JTextField telnotext;
    // End of variables declaration//GEN-END:variables

    
}
