/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import database.IBilgicontroller;
import database.transactions.FaturaOdemeleri;
import database.transactions.HesapBilgileri;
import gui.ayarlar.Actionayarlari;
import gui.ayarlar.Butonayarlari;
import gui.ayarlar.Dialog;
import gui.ayarlar.IDuzenleyici;
import java.awt.Color;
import java.awt.Component;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author EYMEN SEZEN
 */
public final class odemeekrani extends javax.swing.JFrame implements IDuzenleyici,IBilgicontroller{

    /**
     * Creates new form odemeekrani
     */
    private FaturaOdemeleri faturaodemeleriObject =null;
    
    
    public odemeekrani() {
        initComponents();
        getedits();
        
    }

    @Override
    public void getedits() {
        this.setFocusable(true);
        this.setLocationRelativeTo(null);
         /**/
        this.setResizable(false);
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
//OPSİYONELLER
        this.kullanicilabel.setText("Sayın:"+gethesapbilgileri().getAdsoyad());
        this.elektrikborcu.setText(String.valueOf(gethesapbilgileri().getElektrikfat()));
        this.suborcu.setText(String.valueOf(gethesapbilgileri().getSufat()));
        this.doğalgazborcu.setText(String.valueOf(gethesapbilgileri().getDoğalgazfat()));
        this.internetborcu.setText(String.valueOf(gethesapbilgileri().getInternetfat()));
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ödemeekranıpanel = new javax.swing.JPanel();
        kullanicilabel = new javax.swing.JLabel();
        faturalabel = new javax.swing.JLabel();
        elektriködemebutton = new javax.swing.JButton();
        elektrikborcu = new javax.swing.JLabel();
        faturalabel1 = new javax.swing.JLabel();
        doğalgazborcu = new javax.swing.JLabel();
        doğalgazödemebutton = new javax.swing.JButton();
        faturalabel2 = new javax.swing.JLabel();
        suborcu = new javax.swing.JLabel();
        suödemebutton = new javax.swing.JButton();
        faturalabel3 = new javax.swing.JLabel();
        internetborcu = new javax.swing.JLabel();
        internetödemebutton = new javax.swing.JButton();
        cıkıslabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ödemeekranıpanel.setBackground(new java.awt.Color(204, 204, 255));

        kullanicilabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        kullanicilabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        kullanicilabel.setText("Sayın [KULLANICI ADI SOYADI]");

        faturalabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        faturalabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        faturalabel.setText("TOPLAM ELEKTRİK FATURASI BORCU:");

        elektriködemebutton.setBackground(new java.awt.Color(255, 51, 51));
        elektriködemebutton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        elektriködemebutton.setText("ÖDE");
        elektriködemebutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        elektriködemebutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                elektriködemebuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                elektriködemebuttonMouseExited(evt);
            }
        });
        elektriködemebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elektriködemebuttonActionPerformed(evt);
            }
        });

        elektrikborcu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        elektrikborcu.setForeground(new java.awt.Color(51, 51, 255));
        elektrikborcu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        elektrikborcu.setText("[BORÇ]");

        faturalabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        faturalabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        faturalabel1.setText("TOPLAM SU FATURASI BORCU:");

        doğalgazborcu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        doğalgazborcu.setForeground(new java.awt.Color(0, 51, 255));
        doğalgazborcu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        doğalgazborcu.setText("[BORÇ]");

        doğalgazödemebutton.setBackground(new java.awt.Color(255, 51, 51));
        doğalgazödemebutton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        doğalgazödemebutton.setText("ÖDE");
        doğalgazödemebutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        doğalgazödemebutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                doğalgazödemebuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                doğalgazödemebuttonMouseExited(evt);
            }
        });
        doğalgazödemebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doğalgazödemebuttonActionPerformed(evt);
            }
        });

        faturalabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        faturalabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        faturalabel2.setText("TOPLAM DOĞALGAZ FATURASI BORCU:");

        suborcu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        suborcu.setForeground(new java.awt.Color(0, 51, 255));
        suborcu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        suborcu.setText("[BORÇ]");

        suödemebutton.setBackground(new java.awt.Color(255, 51, 51));
        suödemebutton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        suödemebutton.setText("ÖDE");
        suödemebutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        suödemebutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                suödemebuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                suödemebuttonMouseExited(evt);
            }
        });
        suödemebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suödemebuttonActionPerformed(evt);
            }
        });

        faturalabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        faturalabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        faturalabel3.setText("TOPLAM İNTERNET FATURASI BORCU:");

        internetborcu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        internetborcu.setForeground(new java.awt.Color(0, 51, 255));
        internetborcu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        internetborcu.setText("[BORÇ]");

        internetödemebutton.setBackground(new java.awt.Color(255, 51, 51));
        internetödemebutton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        internetödemebutton.setText("ÖDE");
        internetödemebutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        internetödemebutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                internetödemebuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                internetödemebuttonMouseExited(evt);
            }
        });
        internetödemebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                internetödemebuttonActionPerformed(evt);
            }
        });

        cıkıslabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/iconlar/cıkısicon.png"))); // NOI18N
        cıkıslabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cıkıslabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cıkıslabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ödemeekranıpanelLayout = new javax.swing.GroupLayout(ödemeekranıpanel);
        ödemeekranıpanel.setLayout(ödemeekranıpanelLayout);
        ödemeekranıpanelLayout.setHorizontalGroup(
            ödemeekranıpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ödemeekranıpanelLayout.createSequentialGroup()
                .addGroup(ödemeekranıpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ödemeekranıpanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(ödemeekranıpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ödemeekranıpanelLayout.createSequentialGroup()
                                .addComponent(faturalabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(internetborcu, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(internetödemebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ödemeekranıpanelLayout.createSequentialGroup()
                                .addComponent(faturalabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(doğalgazborcu, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(doğalgazödemebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ödemeekranıpanelLayout.createSequentialGroup()
                                .addComponent(faturalabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(suborcu, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(suödemebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ödemeekranıpanelLayout.createSequentialGroup()
                                .addComponent(faturalabel, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(elektrikborcu, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(elektriködemebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(ödemeekranıpanelLayout.createSequentialGroup()
                        .addComponent(cıkıslabel1)
                        .addGap(24, 24, 24)
                        .addComponent(kullanicilabel, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        ödemeekranıpanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {faturalabel, faturalabel1, faturalabel2, faturalabel3});

        ödemeekranıpanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {doğalgazödemebutton, elektriködemebutton, internetödemebutton, suödemebutton});

        ödemeekranıpanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {doğalgazborcu, elektrikborcu, internetborcu, suborcu});

        ödemeekranıpanelLayout.setVerticalGroup(
            ödemeekranıpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ödemeekranıpanelLayout.createSequentialGroup()
                .addGroup(ödemeekranıpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kullanicilabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cıkıslabel1))
                .addGap(43, 43, 43)
                .addGroup(ödemeekranıpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(elektriködemebutton)
                    .addComponent(elektrikborcu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(faturalabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(ödemeekranıpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(suödemebutton)
                    .addComponent(suborcu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(faturalabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(ödemeekranıpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doğalgazödemebutton)
                    .addComponent(doğalgazborcu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(faturalabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(ödemeekranıpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(faturalabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(internetborcu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(internetödemebutton))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        ödemeekranıpanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {faturalabel, faturalabel1, faturalabel2, faturalabel3});

        ödemeekranıpanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {doğalgazödemebutton, elektriködemebutton, internetödemebutton, suödemebutton});

        ödemeekranıpanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {doğalgazborcu, elektrikborcu, internetborcu, suborcu});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ödemeekranıpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ödemeekranıpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void SetBgFg (Component c)//buton renklendirmeleri için
    {
        Butonayarlari.setBgFg((JButton)c, Color.black, Color.white);
    }
    private void suödemebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suödemebuttonActionPerformed
    double suBorcu=Double.valueOf(this.suborcu.getText());//elektrik borcunu double olarak bir değişkene atama işlemi
        if(this.faturaOncedenOdendiMi(suBorcu))
        {
        Dialog.ozelMesajGoster(this, "Su Faturanız daha önce ödendi!");
        }
        else
                {
            this.faturayiOde("su", suBorcu);
                }
    }//GEN-LAST:event_suödemebuttonActionPerformed

    private void internetödemebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_internetödemebuttonActionPerformed
        double internetBorcu=Double.valueOf(this.internetborcu.getText());//elektrik borcunu double olarak bir değişkene atama işlemi
        if(this.faturaOncedenOdendiMi(internetBorcu))
        {
        Dialog.ozelMesajGoster(this, "İnternet Faturanız daha önce ödendi!");
        }
        else
                {
            this.faturayiOde("internet", internetBorcu);
                }
    }//GEN-LAST:event_internetödemebuttonActionPerformed

    private void elektriködemebuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elektriködemebuttonMouseEntered
        this.SetBgFg(evt.getComponent());
    }//GEN-LAST:event_elektriködemebuttonMouseEntered

    private void elektriködemebuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elektriködemebuttonMouseExited
        Butonayarlari.OriginalSetBgFg((JButton)evt.getComponent());
    }//GEN-LAST:event_elektriködemebuttonMouseExited

    private void suödemebuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suödemebuttonMouseEntered
         this.SetBgFg(evt.getComponent());
    }//GEN-LAST:event_suödemebuttonMouseEntered

    private void suödemebuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suödemebuttonMouseExited
        Butonayarlari.OriginalSetBgFg((JButton)evt.getComponent());//eski renk
    }//GEN-LAST:event_suödemebuttonMouseExited

    private void doğalgazödemebuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doğalgazödemebuttonMouseEntered
         this.SetBgFg(evt.getComponent());
    }//GEN-LAST:event_doğalgazödemebuttonMouseEntered

    private void doğalgazödemebuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doğalgazödemebuttonMouseExited
        Butonayarlari.OriginalSetBgFg((JButton)evt.getComponent());
    }//GEN-LAST:event_doğalgazödemebuttonMouseExited

    private void internetödemebuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_internetödemebuttonMouseEntered
         this.SetBgFg(evt.getComponent());
    }//GEN-LAST:event_internetödemebuttonMouseEntered

    private void internetödemebuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_internetödemebuttonMouseExited
        Butonayarlari.OriginalSetBgFg((JButton)evt.getComponent());
    }//GEN-LAST:event_internetödemebuttonMouseExited

    private void elektriködemebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elektriködemebuttonActionPerformed
        double elektrikBorcu=Double.valueOf(this.elektrikborcu.getText());//elektrik borcunu double olarak bir değişkene atama işlemi
        if(this.faturaOncedenOdendiMi(elektrikBorcu))
        {
        Dialog.ozelMesajGoster(this, "Elektrik Faturanız daha önce ödendi!");
        }
        else
                {
            this.faturayiOde("elektrik", elektrikBorcu);
                }
    }//GEN-LAST:event_elektriködemebuttonActionPerformed

    private void doğalgazödemebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doğalgazödemebuttonActionPerformed
       double doğalgazBorcu=Double.valueOf(this.doğalgazborcu.getText());//elektrik borcunu double olarak bir değişkene atama işlemi
        if(this.faturaOncedenOdendiMi(doğalgazBorcu))
        {
        Dialog.ozelMesajGoster(this, "Doğalgaz Faturanız daha önce ödendi!");
        }
        else
                {
            this.faturayiOde("doğalgaz", doğalgazBorcu);
                }
    }//GEN-LAST:event_doğalgazödemebuttonActionPerformed

    private void cıkıslabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cıkıslabel1MouseClicked
               Actionayarlari.setVisible(this, new hesapekrani());

    }//GEN-LAST:event_cıkıslabel1MouseClicked
    private boolean faturaOncedenOdendiMi(double odenecekTutar)
    {
        
        
    return odenecekTutar==0.0;
    
    }
    private void faturayiOde(String faturaAdı,double FaturaTutarı)
    {
    this.getFaturaodemeleriObject().setFaturaIsmi(faturaAdı);
    this.getFaturaodemeleriObject().setFaturaTutarı(FaturaTutarı);
    if(getFaturaodemeleriObject().faturaOdendiMi())
    {
    Dialog.ozelMesajGoster(this, "FATURANIZ BAŞARIYLA ÖDENDİ.");
    Actionayarlari.setVisible(this, new hesapekrani());
    } 
    else
    {
    Dialog.ozelMesajGoster(this, "Faturanız ödenemedi.");
    }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(odemeekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(odemeekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(odemeekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(odemeekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new odemeekrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cıkıslabel1;
    private javax.swing.JLabel doğalgazborcu;
    private javax.swing.JButton doğalgazödemebutton;
    private javax.swing.JLabel elektrikborcu;
    private javax.swing.JButton elektriködemebutton;
    private javax.swing.JLabel faturalabel;
    private javax.swing.JLabel faturalabel1;
    private javax.swing.JLabel faturalabel2;
    private javax.swing.JLabel faturalabel3;
    private javax.swing.JLabel internetborcu;
    private javax.swing.JButton internetödemebutton;
    private javax.swing.JLabel kullanicilabel;
    private javax.swing.JLabel suborcu;
    private javax.swing.JButton suödemebutton;
    private javax.swing.JPanel ödemeekranıpanel;
    // End of variables declaration//GEN-END:variables

    @Override
    public boolean bilgilergecerlimi() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public HesapBilgileri gethesapbilgileri() {
     return HesapBilgileri.getInstance();
    }

    public FaturaOdemeleri getFaturaodemeleriObject() {
        if(this.faturaodemeleriObject==null)
        {
            faturaodemeleriObject=new FaturaOdemeleri();
      
    }
        return faturaodemeleriObject;
    }
    
}
