/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import database.IBilgicontroller;
import database.transactions.HesapBilgileri;
import database.transactions.SifreYenileme;
import gui.ayarlar.Actionayarlari;
import gui.ayarlar.Butonayarlari;
import gui.ayarlar.Dialog;
import gui.ayarlar.IDuzenleyici;
import gui.ayarlar.Textayarlari;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;

/**
 *
 * @author EYMEN SEZEN
 */
public class şifreyenilemeekrani extends javax.swing.JFrame implements IDuzenleyici, IBilgicontroller {

    /**
     * Creates new form şifreyenilemeekrani
     */
    private SifreYenileme sifreYenilemeObject = null;
    public şifreyenilemeekrani() {
        initComponents();
        getedits();
    }

    public JPasswordField getEskişifretext() {

        return eskişifretext;
    }

    private boolean isEnabledeskişifretext() {

        return this.getEskişifretext().isEnabled();//textin aktifliğini sorgulayacağız..
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        şifreyenilemepanel = new javax.swing.JPanel();
        cıkıslabel = new javax.swing.JLabel();
        şifreyenilemelabel = new javax.swing.JLabel();
        tclabel = new javax.swing.JLabel();
        tctext = new javax.swing.JTextField();
        telnolabel = new javax.swing.JLabel();
        telnotext = new javax.swing.JTextField();
        güvenliklabel = new javax.swing.JLabel();
        güvenliktext = new javax.swing.JTextField();
        yenişifrelabel = new javax.swing.JLabel();
        yenişifretekrarlabel = new javax.swing.JLabel();
        eskişifrelabel = new javax.swing.JLabel();
        eskişifretext = new javax.swing.JPasswordField();
        yenişifretext = new javax.swing.JPasswordField();
        yenişifretekrartext = new javax.swing.JPasswordField();
        onaybutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        şifreyenilemepanel.setBackground(new java.awt.Color(204, 204, 255));

        cıkıslabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/iconlar/cıkısicon.png"))); // NOI18N
        cıkıslabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cıkıslabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cıkıslabelMouseClicked(evt);
            }
        });

        şifreyenilemelabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        şifreyenilemelabel.setText("ŞİFRE YENİLEME");

        tclabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tclabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tclabel.setText("TC No:");

        telnolabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        telnolabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        telnolabel.setText("Telefon No:");

        güvenliklabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        güvenliklabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        güvenliklabel.setText("Güvenlik Sorusu Cevabı:");

        yenişifrelabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        yenişifrelabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        yenişifrelabel.setText("Yeni Şifre:");

        yenişifretekrarlabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        yenişifretekrarlabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        yenişifretekrarlabel.setText("Yeni Şifre Tekrar:");

        eskişifrelabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        eskişifrelabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        eskişifrelabel.setText("Eski Şifre:");

        onaybutton.setBackground(new java.awt.Color(0, 0, 255));
        onaybutton.setText("Şifreyi Yenile");
        onaybutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        onaybutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                onaybuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                onaybuttonMouseExited(evt);
            }
        });
        onaybutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onaybuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout şifreyenilemepanelLayout = new javax.swing.GroupLayout(şifreyenilemepanel);
        şifreyenilemepanel.setLayout(şifreyenilemepanelLayout);
        şifreyenilemepanelLayout.setHorizontalGroup(
            şifreyenilemepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(şifreyenilemepanelLayout.createSequentialGroup()
                .addComponent(cıkıslabel)
                .addGroup(şifreyenilemepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(şifreyenilemepanelLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(şifreyenilemepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(şifreyenilemepanelLayout.createSequentialGroup()
                                .addComponent(telnolabel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(telnotext, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(şifreyenilemepanelLayout.createSequentialGroup()
                                .addComponent(tclabel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(tctext, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(şifreyenilemepanelLayout.createSequentialGroup()
                        .addGroup(şifreyenilemepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(güvenliklabel, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eskişifrelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yenişifrelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yenişifretekrarlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(şifreyenilemepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(güvenliktext, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eskişifretext, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yenişifretext, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yenişifretekrartext, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(şifreyenilemepanelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(onaybutton)))))
                .addGap(0, 80, Short.MAX_VALUE))
            .addGroup(şifreyenilemepanelLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(şifreyenilemelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        şifreyenilemepanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {tclabel, telnolabel});

        şifreyenilemepanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {eskişifretext, güvenliktext, tctext, telnotext, yenişifretekrartext, yenişifretext});

        şifreyenilemepanelLayout.setVerticalGroup(
            şifreyenilemepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(şifreyenilemepanelLayout.createSequentialGroup()
                .addGroup(şifreyenilemepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(şifreyenilemelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cıkıslabel))
                .addGap(18, 18, 18)
                .addGroup(şifreyenilemepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tclabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tctext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(şifreyenilemepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telnolabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telnotext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(şifreyenilemepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(güvenliklabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(güvenliktext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(şifreyenilemepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eskişifrelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eskişifretext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(şifreyenilemepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yenişifrelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yenişifretext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(şifreyenilemepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yenişifretekrarlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yenişifretekrartext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(onaybutton)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        şifreyenilemepanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {eskişifretext, güvenliklabel, güvenliktext, tclabel, tctext, telnolabel, telnotext, yenişifretekrartext, yenişifretext});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(şifreyenilemepanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(şifreyenilemepanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cıkıslabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cıkıslabelMouseClicked
        if (isEnabledeskişifretext()) {

            Actionayarlari.setVisible(this, new ayarlarekrani());
        } else {
            Actionayarlari.setVisible(this, new girisekrani());
        }
    }//GEN-LAST:event_cıkıslabelMouseClicked

    private void onaybuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onaybuttonActionPerformed
        if(this.bilgilergecerlimi())
        {
            this.sifreyiYenile();
        }
        else
        {
        Dialog.bosOlamazMesajiGoster(this);
        }

    }//GEN-LAST:event_onaybuttonActionPerformed
    private void sifreyiYenile()
    {
    String yenisifre=String.valueOf(this.yenişifretext.getPassword());
    String yenisifreTekrar=String.valueOf(this.yenişifretekrartext.getPassword());
    if(yenisifre.equals(yenisifreTekrar))
    {
    this.sifreyiOnayla();
    }
    else
    {
    Dialog.ozelMesajGoster(this, "Şifreler uyuşmuyor lütfen tekrar deneyiniz...");
    }
    }
    private void sifreyiOnayla()
    {
        this.getSifreYenilemeObject().setTcNo(this.tctext.getText());
        this.getSifreYenilemeObject().setTelNo(this.telnotext.getText());
        this.getSifreYenilemeObject().setGuvenlikCevap(this.güvenliktext.getText());
        if(this.isEnabledeskişifretext()) {
            this.getSifreYenilemeObject().setEskiSifre(String.valueOf(this.eskişifretext.getPassword()));
        }
        this.getSifreYenilemeObject().setYeniSifre(String.valueOf(this.yenişifretext.getPassword()));
        
        if(this.getSifreYenilemeObject().sifreYenilendiMi()) {
            Dialog.ozelMesajGoster(this, "Şifreniz başarıyla yenilenmiştir.");
            if(this.isEnabledeskişifretext()) {
                Actionayarlari.setVisible(this, new hesapekrani());
            } else {
                Actionayarlari.setVisible(this, new girisekrani());
            }
        } else {
            Dialog.ozelMesajGoster(this, "Şifreniz yenilenemedi!\n"
                    + "Lütfen bilgilerinizi kontrol edin!");
        }

    
    }
    
    
    private void onaybuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onaybuttonMouseEntered
        Butonayarlari.setBgFg(onaybutton, Color.cyan, Color.red);
    }//GEN-LAST:event_onaybuttonMouseEntered

    private void onaybuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onaybuttonMouseExited
        Butonayarlari.OriginalSetBgFg(onaybutton);
    }//GEN-LAST:event_onaybuttonMouseExited

    @Override
    public void getedits() {
        this.setFocusable(true);
        this.setLocationRelativeTo(null);
         /**/
        this.setResizable(false);
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
//OPSİYONELLER
        Textayarlari.setonlynumber(tctext);
        Textayarlari.setlimitayarla(tctext, 11);
        Textayarlari.setonlynumber(telnotext);
        Textayarlari.setlimitayarla(telnotext, 11);
        if(gethesapbilgileri().getKullanıcıid()==0)
        {
        this.eskişifretext.setEnabled(false);
        }

    }

    @Override
    public boolean bilgilergecerlimi() {
        return (Textayarlari.textalanlarıDoluMu(this.şifreyenilemepanel));  
    }

    @Override
    public HesapBilgileri gethesapbilgileri() {
        return HesapBilgileri.getInstance();
        }

    public SifreYenileme getSifreYenilemeObject() {
        if(this.sifreYenilemeObject==null)
        {
        sifreYenilemeObject=new SifreYenileme();
        }  
        return sifreYenilemeObject;
    }
    
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(şifreyenilemeekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(şifreyenilemeekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(şifreyenilemeekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(şifreyenilemeekrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new şifreyenilemeekrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cıkıslabel;
    private javax.swing.JLabel eskişifrelabel;
    private javax.swing.JPasswordField eskişifretext;
    private javax.swing.JLabel güvenliklabel;
    private javax.swing.JTextField güvenliktext;
    private javax.swing.JButton onaybutton;
    private javax.swing.JLabel tclabel;
    private javax.swing.JTextField tctext;
    private javax.swing.JLabel telnolabel;
    private javax.swing.JTextField telnotext;
    private javax.swing.JLabel yenişifrelabel;
    private javax.swing.JLabel yenişifretekrarlabel;
    private javax.swing.JPasswordField yenişifretekrartext;
    private javax.swing.JPasswordField yenişifretext;
    private javax.swing.JLabel şifreyenilemelabel;
    private javax.swing.JPanel şifreyenilemepanel;
    // End of variables declaration//GEN-END:variables

}
